version: "3.8"
services:
  distributed-project-postgres:
    container_name: distributed-project-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    build: .
    ports:
      - "5444:5432"
    volumes:
      - distributed-project-postgres-volume:/var/lib/postgresql/data
volumes:
  distributed-project-postgres-volume:
    